# Generated by Django 5.0.7 on 2024-07-15 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_faq_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="category",
        ),
    ]
