# Generated by Django 5.0.7 on 2024-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0003_remove_faq_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[("general", "General"), ("corporate", "Corporate")],
                default="general",
                max_length=10,
            ),
        ),
    ]
