# Generated by Django 5.0.7 on 2024-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="detail_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="", max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="receive_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="receive_sms",
            field=models.BooleanField(default=False),
        ),
    ]
