# Generated by Django 5.0.7 on 2024-07-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_address_customuser_detail_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="business_registration_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
