# Generated by Django 5.0.7 on 2024-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_customuser_userid_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
