# Generated by Django 5.0.7 on 2024-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("business", "Business"),
                    ("admin", "Admin"),
                ],
                default="individual",
                max_length=10,
            ),
        ),
    ]
