# Generated by Django 5.0.7 on 2024-07-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="order_requests_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="orders_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
