# Generated by Django 5.0.7 on 2024-07-18 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/before/")),
                (
                    "before_image_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("neck_line", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sleeve_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pattern", models.CharField(blank=True, max_length=50, null=True)),
                ("pocket", models.CharField(blank=True, max_length=50, null=True)),
                ("zip", models.CharField(blank=True, max_length=50, null=True)),
                ("button", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "addt_design",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dalle_image_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("prompt", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
