# Generated by Django 5.0.7 on 2024-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/before/")),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="images/after/"),
                ),
                ("material", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
                ("neck_line", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sleeve_length",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pattern", models.CharField(blank=True, max_length=255, null=True)),
                ("pocket", models.CharField(blank=True, max_length=255, null=True)),
                ("zip", models.CharField(blank=True, max_length=255, null=True)),
                ("button", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "addt_design",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("full_prompt", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedImage",
        ),
    ]
