# Generated by Django 5.0.7 on 2024-07-15 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0002_orderinfo_delete_uploadedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinfo",
            name="full_prompt",
        ),
    ]
