# Generated by Django 5.0.7 on 2024-07-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0003_remove_orderinfo_full_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinfo",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="addt_design",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="button",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="neck_line",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="pattern",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="pocket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="sleeve_length",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="zip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
