# Generated by Django 5.0.7 on 2024-07-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0003_uploadedimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="dalle_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
