# Generated by Django 5.0.7 on 2024-07-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0004_uploadedimage_dalle_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
