# Generated by Django 5.0.7 on 2024-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0005_uploadedimage_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="request_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="response_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
