# Generated by Django 5.0.7 on 2024-07-16 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0006_uploadedimage_request_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="response_data",
        ),
    ]
