# Generated by Django 5.0.7 on 2024-07-16 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0007_remove_uploadedimage_response_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="request_data",
        ),
    ]
