# Generated by Django 5.0.7 on 2024-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0008_remove_uploadedimage_request_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="dalle_image_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
