# Generated by Django 5.0.7 on 2024-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyze", "0009_alter_uploadedimage_dalle_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedImage",
            new_name="OrderInfo",
        ),
    ]
