# Generated by Django 5.0.7 on 2024-07-15 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("shirt", "셔츠/티셔츠"), ("sweater", "스웨터")], max_length=10
                    ),
                ),
                (
                    "sleeve_length",
                    models.CharField(
                        choices=[
                            ("short", "짧은 소매"),
                            ("long", "긴 소매"),
                            ("sleeveless", "민소매"),
                        ],
                        max_length=15,
                    ),
                ),
                ("neckline", models.CharField(max_length=20)),
                (
                    "button",
                    models.CharField(
                        blank=True,
                        choices=[("none", "없음"), ("half", "하프"), ("full", "풀")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "zipper",
                    models.CharField(
                        blank=True,
                        choices=[("none", "없음"), ("half", "하프"), ("full", "풀")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pocket",
                    models.CharField(
                        blank=True,
                        choices=[("remove", "제거"), ("right", "오른쪽"), ("left", "왼쪽")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "etc",
                    models.CharField(
                        choices=[("crop", "크롭"), ("reduce", "폼 줄이기")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
