# Generated by Django 5.0.7 on 2024-07-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_b", "0005_remove_receiveorder_business_user_and_more"),
        ("orders_u", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders_b.company",
            ),
            preserve_default=False,
        ),
    ]
