# Generated by Django 5.0.7 on 2024-07-15 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders_u", "0002_orderuser_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderuser",
            name="button",
        ),
        migrations.RemoveField(
            model_name="orderuser",
            name="zipper",
        ),
    ]
