# Generated by Django 5.0.7 on 2024-07-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_u", "0003_remove_orderuser_button_remove_orderuser_zipper"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="color",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderuser",
            name="material",
            field=models.CharField(
                choices=[
                    ("cotton", "Cotton"),
                    ("polyester", "Polyester"),
                    ("wool", "Wool"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
