# Generated by Django 5.0.7 on 2024-07-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_number", models.AutoField(primary_key=True, serialize=False)),
                ("customer_nickname", models.CharField(max_length=100)),
                ("customer_order_number", models.CharField(max_length=100)),
                (
                    "original_category",
                    models.CharField(
                        choices=[
                            ("category1", "Category 1"),
                            ("category2", "Category 2"),
                            ("category3", "Category 3"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "desired_category",
                    models.CharField(
                        choices=[
                            ("result1", "Result 1"),
                            ("result2", "Result 2"),
                            ("result3", "Result 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
