# Generated by Django 5.0.7 on 2024-07-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_nickname", models.CharField(max_length=100)),
                ("customer_order_number", models.CharField(max_length=100)),
                (
                    "clothing_category",
                    models.CharField(
                        choices=[
                            ("shirt", "셔츠"),
                            ("tshirt", "티셔츠"),
                            ("sweater", "스웨터"),
                        ],
                        max_length=100,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
