# Generated by Django 5.0.7 on 2024-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_b", "0002_customuser_receiveorder_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiveorder",
            name="customer_order_number",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
