# Generated by Django 5.0.7 on 2024-07-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_b", "0003_receiveorder_customer_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiveorder",
            name="clothing_category",
            field=models.CharField(
                choices=[("shirt", "셔츠"), ("tshirt", "티셔츠"), ("sweater", "스웨터")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
