# Generated by Django 5.0.7 on 2024-07-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_b", "0005_remove_receiveorder_business_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business_registration_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
