# Generated by Django 5.0.7 on 2024-07-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders_b",
            "0007_company_address_company_detail_address_company_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="detail_address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
