# Generated by Django 5.0.7 on 2024-07-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_nickname", models.CharField(max_length=150)),
                ("material", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fixed_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_nickname", models.CharField(max_length=150)),
                ("material", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("ACCEPTED", "수락"),
                            ("REJECTED", "거절"),
                            ("COMPLETED", "완료"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
